server:
  port: 8080

spring:
  application:
    name: gateway-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/registry_demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: order-route
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: product-route
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: console-route
          uri: lb://console-service
          predicates:
            - Path=/console/**
          filters:
            - StripPrefix=1

mysql-registry:
  enabled: true
